### ISSUE TITLE
Links to latest PDF & EPUB files

### ISSUE THREAD

**Issue by fzzr-** [HaxeFoundation/HaxeManual#129]
I think it would be fine if we had in the footer links to [pdf](https://github.com/HaxeFoundation/HaxeManual/raw/master/HaxeDoc.pdf) & [epub](https://github.com/HaxeFoundation/HaxeManual/blob/master/HaxeManual.epub?raw=true) files.

Also will be great to start versioning and releases for manual. And to upload docs (pdf, pub, mobi, etc..) to [releases](https://github.com/HaxeFoundation/HaxeManual/releases).

Also some people wants classic for *nix console man (`$ man haxe`).

**Comment by Simn** [comment]
In what header?

**Comment by fzzr-** [comment]
I mean in footer of site where manual is.

**Comment by Simn** [comment]
That would be an issue for haxe.org, but I don't really want to promote these formats until I'm satisfied with them.

I also have no interest in any form of release process for this. The manual itself has "since Haxe x.y.z" tags in places it matters which really aren't too many.

As for manpages, I don't have any real objection but I also don't want to look into it myself. If there's any interest for that I'm sure someone will send a pull request at some point.
