### ISSUE TITLE
Static extensions do not extend to values in anonymous data structures.

### ISSUE THREAD

**Issue by indolering** [HaxeFoundation/HaxeManual#209]
Just a TODO for myself.

**Comment by Simn** [comment]
Good because I don't understand what you mean.

**Comment by markknol** [comment]
Is this true? I mean static extensions could be used on any kind of type right? Interfaces, typedefs, primitives, even anons? As long as the first argument  of the static function has that type?

**Comment by indolering** [comment]
@markknol it didn't work when I tried using it on a field within an anonymous data structure:

```
anon.stringfield.staticMethod();
```

The `staticMethod` declared a string parameter and I checked the `anon.stringfield` type before attempting to access it.

**Comment by markknol** [comment]
Can you make an example of that? I wonder if it's a bug or something that should be documented.

**Comment by indolering** [comment]
@markknol [Here you go:](http://try.haxe.org/#1aba4)

    using Test.IntExtender;
    import haxe.Json;

    class IntExtender {
      static public function triple(i:Int) {
        return i * 3;
      }
    }

    class Test {
      static public function main() {
          var json = {
            'value': 10
        };
        var anon = Json.parse(Json.stringify(json));
          trace(anon.value); //10
        trace(anon.value.triple()); //Uncaught TypeError: anon.value.triple is not a function,
      }
    }

Just creating an anonymous structure isn't enough, I suspect that the compiler is annotating type information. Haxe could inspect anonymous structures as they are passed but you would still have to worry about external manipulation of the anonymous structure.

**Comment by mrcdk** [comment]
That behavior is already documented here http://haxe.org/manual/types-dynamic.html

**Comment by Simn** [comment]
Indeed

**Comment by indolering** [comment]
I have expertise in technical documentation and we know that people don't read documentation as if it were a book.   They spend ~5 minutes looking for a sections they think is most relevant to the issue at hand.   I spent a few minutes Googling and found the page on static extensions which is where I assumed I would find an answer.  That's a survey sample size of one, but I see no problem with adding a cross reference in this section.

Furthermore, the section on static extensions is factually incorrect:

> There are three requirements for this:
* Both the literal 12 and the first argument of triple are of type Int.
* The class IntExtender is brought into context through using Main.IntExtender.
* Int does not have a triple field by itself (if it had, that field would take priority over the static extension).

I specifically tested an anonymous field's type before attempting to use a static extension and it failed.

Finally, please do not close my tickets without soliciting my input.

**Comment by mrcdk** [comment]
I don't see a problem in the static extension part of the manual.

What you seem to be missing is that you are working with a `Dynamic` in your example (well, a unknown type because the compiler won't ever unify with a `Dynamic` without you telling it explicitly) which basically means "hey compiler, I know what I'm doing so don't bug me with your nonsense" and, as far as I can see, you don't really know what you are doing :sweat_smile:

**Comment by nadako** [comment]
@indolering the problem in that try.haxe.org example is not with static extensions, but with the fact that `Json.parse` returns `Dynamic` type.

**Comment by nadako** [comment]
Oh, @mrcdk was faster.

**Comment by mrcdk** [comment]
Here is how I would solve the problem on your example http://try.haxe.org/#0D9fe As you can see, you have to tell the compiler that the field is an `Int` so it can work its magic

**Comment by indolering** [comment]
*sigh* You are basically complaining that it's users who don't understand the typing system.  God forbid the documentation spends a few lines trying to help users understand when a static extension won't work.

**Comment by mrcdk** [comment]
`¯\_(ツ)_/¯`

**Comment by indolering** [comment]
> ¯\_(ツ)_/¯

I consider myself an A-grade usability engineer but a C-grade programmer.  The fact that I'm not very good at programming is a valuable asset because I can provide a different perspective.  I have a different skillset that I'm trying to use to make your documentation better.

But insulting me and shutting down my tickets?  Fuck this community.

**Comment by nadako** [comment]
I'm not sure about the whole "insulting" thing, but this particular issue is plain wrong (just look at its title) and is therefore closed as there's nothing to do here.

If you think there's something to be documented to make people not make that mistake you did, that should go to section about `Dynamic` anyway, but there's already this statement that explains the reason perfectly IMO:

> The compiler can no longer type-check assignments, function calls and other constructs where specific types are expected.

**Comment by jonasmalacofilho** [comment]
How about changing

> 1. Both the literal `12` and the first argument of `triple` are of type `Int`.

slightly so that it reminds the user that types are a compile time thing and that there are rules to type inference:

1. Both the literal `12` and the first argument of `triple` are known to be of type `Int`?

--- 

> You are basically complaining that it's users who don't understand the typing system. God forbid the documentation spends a few lines trying to help users understand when a static extension won't work.

The issue is how to achieve this friendless without restating everywhere all the user should know about the type system.  Yes, many users just skip to a particular section, but the assumption that this behaviour should yield an equally precise understanding of how the language works is absurd.  

Actually, if every section just restated all the context to it, readers would then shift to skipping to subsections they perceived most relevant...

> But insulting me and shutting down my tickets? What the hell?

The end read "Fuck this community" originally.  Please don't do act like that.

Yes, it would be marginally more polite and desirable to check if your problem had been solved before closing the issue.  On the other hand, static extensions DO work with values in anonymous data structures, and the manual does not suggest otherwise; everything after your _misconception_ has been explained is a discussion to see how could we prevent it from happening again in the future.

**Comment by nadako** [comment]
> Both the literal 12 and the first argument of triple are *known* to be of type Int

This is a nice change IMO, we should add it

**Comment by markknol** [comment]
Thanks for this addition!

**Comment by indolering** [comment]
>The end read "Fuck this community" originally. Please don't do act like that.

I changed that immediately because it was too harsh, but that's exactly how I felt.  

> slightly so that it reminds the user that types are a compile time thing and that there are rules to type inference:

That's where this ticket was headed from the beginning except that I wrote "anonymous" instead of "dynamic".

>  Both the literal 12 and the first argument of triple are known to be of type Int

But in my case I actually checked the type of the field at runtime, so it has to be known at compile time.

**Comment by nadako** [comment]
How it "has to" be known at compile time if you're dealing with result of `String->Dynamic` function which is `Json.parse`? The type of result is bound to a monomorph (unknown type) so static extensions cannot be applied.

**Comment by mrcdk** [comment]
I don't really like the wording of the proposed change, known by whom? the compiler? the runtime? the user?... as we can see, it is still not clear to @indolering. I actually prefer the old version because it doesn't add that uncertainty and specify that both, `12` and the first argument of `triple()`, have to be typed as `Int`.

Now, @indolering. Static extensions are a compile-time feature, they will do their magic at compile time and not at runtime. This means that, even if you are sure that the runtime type of the `anon.value` is `Int` if the compiler can't infer it by you explicitly telling it that the type is `Int` or by itself, static extensions won't work. The compiler will check the type of `anon.value` but it will find that it's unknown so it won't apply the static extension magic.

Why the compiler can infer the type of `anon.value` to `Int`? Well, the type of `anom.value` is unknown to the compiler because `Dynamic` is in the middle of your example by the use of `Json.parse()` http://api.haxe.org/haxe/Json.html#parse (Notice how the function returns a `Dynamic`) As we know, from the first link I posted ( http://haxe.org/manual/types-dynamic.html ), `Dynamic` is a special type. As I posted before, `Dynamic` is telling the compiler: "hey compiler, I (the developer) know what I'm doing so don't bug me with your nonsense" so the compiler won't apply any optimization, won't check the type, won't catch typos at compile time,... 

Also, you aren't checking the type at runtime, you are checking the value which really doesn't tell anything about the type. In your example it can be an `Int` or a `Float` or even a `String` just printing the value isn't enough. 

The issue was closed without your input because what you stated in the title and the body of it isn't true. You found a "special case" without really understanding the special part of the case. The "special case" is, of course, the usage of `Dynamic`. If we have to warn the reader that `Dynamic` has unexpected results when using it with static extensions, we may as well add a huge header on every section of the manual with that warning because, yes, if you use `Dynamic` with anything else in the language you will have unexpected results and problems at runtime if you aren't careful.

**Comment by jonasmalacofilho** [comment]
> I don't really like the wording of the proposed change, known by whom? the compiler? the runtime? the user?

@mrcdk I was having second thoughts myself, "known to be of type `Int`" is indeed too vague.

The original wording from the manual is quite precise, but assumes an attentive reader that  remembers how the Haxe type system works; even more, a reader that has some experience with typed languages and that does understand the word "type" as a compile time thing.

So...  I still think it's valid to leave some breadcrumbs around that remind users other than these to read (or at least think about) what "is of type `Int`" means.  Perhaps something like:

 1. Both the literal `12` and the first argument of `triple` are known by the compiler to be of type `Int`.

In fact, I think the manual already employs similar constructions in other places to remind readers of possible difficulties.

In my opinion, if we can find a simple change that @indolering thinks could have prevented his confusion, it would be nice to add it.

**Comment by indolering** [comment]
Hey, I wanted to apologize for my language and abrasive attitude.  I'll get back to contributing once the docs have been converted to markdown.

**Comment by nadako** [comment]
Oh, that reminds me we should actually do that :)
